# https://github.com/bitwarden/clients/blob/main/.github/workflows/build-browser.yml
name: Build Browser

on:
    workflow_call:
        inputs: {}
    workflow_dispatch:
        inputs: {}
    push:
        branches: [master, main]
    schedule:
        # On every Sunday 12:00
        - cron: "0 12 * * 0"

permissions:
    contents: write # To Release

defaults:
    run:
        shell: bash

jobs:
    setup:
        name: Setup
        runs-on: ubuntu-22.04
        outputs:
            latest_browser_tag: ${{ steps.gen_vars.outputs.latest_browser_tag }}
            node_version: ${{ steps.retrieve-node-version.outputs.node_version }}
        steps:
            - name: Check out repo
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Clone real repo
              run: |
                  git clone https://github.com/bitwarden/clients.git

            - name: Get Latest Browser Tag
              id: gen_vars
              working-directory: clients
              run: |
                  # Find all tags and sort by time
                  git fetch --tags
                  tags=$(git tag --sort=-creatordate)
                  # Find "browser" tag
                  latest_browser_tag=""
                  for tag in $tags; do
                      if [[ $tag == *"browser"* ]]; then
                          latest_browser_tag=$tag
                          break
                      fi
                  done

                  echo "latest_browser_tag=$latest_browser_tag" >> $GITHUB_OUTPUT
                  echo "latest_browser_tag=$latest_browser_tag"

            - name: Get Node Version
              id: retrieve-node-version
              working-directory: clients
              run: |
                  NODE_NVMRC=$(cat .nvmrc)
                  NODE_VERSION=${NODE_NVMRC/v/''}
                  echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT

    locales-test:
        name: Locales Test
        runs-on: ubuntu-22.04
        needs:
            - setup
        env:
            _LATEST_BROWSER_TAG: ${{ needs.setup.outputs.latest_browser_tag }}
        steps:
            - name: Check out repo
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Clone real repo
              run: |
                  git clone https://github.com/bitwarden/clients.git

            - name: Setup repo
              working-directory: clients
              run: |
                  git fetch --tags
                  echo "Checking out ${{ env._LATEST_BROWSER_TAG }}"
                  git checkout ${{ env._LATEST_BROWSER_TAG }}

            - name: Testing locales - extName length
              working-directory: clients/apps/browser/
              run: |
                  found_error=false

                  echo "Locales Test"
                  echo "============"
                  echo "extName string must be 40 characters or less"
                  echo
                  for locale in $(ls src/_locales/); do
                    string_length=$(jq '.extName.message | length' src/_locales/$locale/messages.json)
                    if [[ $string_length -gt 40 ]]; then
                      echo "$locale: $string_length"
                      found_error=true
                    fi
                  done

                  if $found_error; then
                    echo
                    echo "Please fix 'extName' for the locales listed above."
                    # exit 1
                  else
                    echo "Test passed!"
                  fi

    build-source:
        name: Build browser source
        runs-on: ubuntu-22.04
        needs:
            - setup
        env:
            _LATEST_BROWSER_TAG: ${{ needs.setup.outputs.latest_browser_tag }}
            _NODE_VERSION: ${{ needs.setup.outputs.node_version }}
        steps:
            - name: Check out repo
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Clone real repo
              run: |
                  git clone https://github.com/bitwarden/clients.git

            - name: Setup repo
              working-directory: clients
              run: |
                  git fetch --tags
                  echo "Checking out ${{ env._LATEST_BROWSER_TAG }}"
                  git checkout ${{ env._LATEST_BROWSER_TAG }}

            - name: Set up Node
              uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
              with:
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
                  node-version: ${{ env._NODE_VERSION }}

            - name: Print environment
              run: |
                  node --version
                  npm --version

            - name: Apply internal patch
              working-directory: clients
              run: |
                  cp ../patches/browser/hasPremiumPersonally.patch .
                  git apply hasPremiumPersonally.patch -v

            - name: Build sources for reviewers
              working-directory: clients
              run: |
                  # Include hidden files in glob copy
                  shopt -s dotglob

                  # Remove ".git" directory
                  rm -r .git

                  # Copy root level files to source directory
                  mkdir browser-source
                  FILES=$(find . -maxdepth 1 -type f)
                  for FILE in $FILES; do cp "$FILE" browser-source/; done

                  # Copy apps/browser to the Browser source directory
                  mkdir -p browser-source/apps/browser
                  cp -r apps/browser/* browser-source/apps/browser

                  # Copy libs to Browser source directory
                  mkdir browser-source/libs
                  cp -r libs/* browser-source/libs

                  zip -r browser-source.zip browser-source

            - name: Upload browser source
              uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
              with:
                  name: browser-source-${{ env._LATEST_BROWSER_TAG }}.zip
                  path: clients/browser-source.zip
                  if-no-files-found: error

    build:
        name: Build
        runs-on: ubuntu-22.04
        needs:
            - setup
            - build-source
        env:
            _LATEST_BROWSER_TAG: ${{ needs.setup.outputs.latest_browser_tag }}
            _NODE_VERSION: ${{ needs.setup.outputs.node_version }}
        strategy:
            matrix:
                include:
                    - name: "chrome"
                      npm_command: "dist:chrome"
                      archive_name: "dist-chrome.zip"
                      artifact_name: "dist-chrome-MV3"
                    - name: "edge"
                      npm_command: "dist:edge"
                      archive_name: "dist-edge.zip"
                      artifact_name: "dist-edge-MV3"
                    - name: "firefox"
                      npm_command: "dist:firefox"
                      archive_name: "dist-firefox.zip"
                      artifact_name: "dist-firefox"
                    # - name: "firefox-mv3"
                    #   npm_command: "dist:firefox:mv3"
                    #   archive_name: "dist-firefox.zip"
                    #   artifact_name: "DO-NOT-USE-FOR-PROD-dist-firefox-MV3"
                    - name: "opera-mv3"
                      npm_command: "dist:opera:mv3"
                      archive_name: "dist-opera.zip"
                      artifact_name: "dist-opera-MV3"
        steps:
            - name: Check out repo
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Clone real repo
              run: |
                  git clone https://github.com/bitwarden/clients.git

            - name: Setup repo
              working-directory: clients
              run: |
                  git fetch --tags
                  echo "Checking out ${{ env._LATEST_BROWSER_TAG }}"
                  git checkout ${{ env._LATEST_BROWSER_TAG }}

            - name: Set up Node
              uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
              with:
                  cache: "npm"
                  cache-dependency-path: "**/package-lock.json"
                  node-version: ${{ env._NODE_VERSION }}

            - name: Print environment
              run: |
                  node --version
                  npm --version

            - name: Download browser source
              uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
              with:
                  name: browser-source-${{ env._LATEST_BROWSER_TAG }}.zip

            - name: Unzip browser source artifact
              run: |
                  unzip browser-source.zip
                  rm browser-source.zip

            - name: NPM setup
              run: npm ci
              working-directory: browser-source/

            - name: Check source file size
              if: ${{ startsWith(matrix.name, 'firefox') }}
              run: |
                  # Declare variable as indexed array
                  declare -a FILES

                  # Search for source files that are greater than 5M
                  TARGET_DIR='./browser-source/apps/browser'
                  while IFS=' ' read -r RESULT; do
                      FILES+=("$RESULT")
                  done < <(find $TARGET_DIR -size +5M)

                  # Validate results and provide messaging
                  if [[ ${#FILES[@]} -ne 0 ]]; then
                      echo "File(s) exceeds size limit: 5MB"
                      for FILE in ${FILES[@]}; do
                          echo "- $(du --si $FILE)"
                      done
                      echo "ERROR Firefox rejects extension uploads that contain files larger than 5MB"
                      # Invoke failure
                      # exit 1
                  fi
                  
            - name: Build extension
              run: npm run ${{ matrix.npm_command }}
              working-directory: browser-source/apps/browser

            - name: Upload extension artifact
              uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
              with:
                  name: ${{ matrix.artifact_name }}-${{ env._LATEST_BROWSER_TAG }}.zip
                  path: browser-source/apps/browser/dist/${{ matrix.archive_name }}
                  if-no-files-found: error

    release:
        name: Release
        runs-on: ubuntu-22.04
        needs:
            - setup
            - build-source
            - build
        env:
            _LATEST_BROWSER_TAG: ${{ needs.setup.outputs.latest_browser_tag }}
        steps:
            - name: mkdir
              run: mkdir -p artifacts

            - name: Download all artifacts
              uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
              with:
                  merge-multiple: true
                  path: artifacts

            - name: Create release
              uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
              continue-on-error: true
              with:
                  artifacts: "artifacts/*"
                  tag: "${{ env._LATEST_BROWSER_TAG }}"
                  name: "${{ env._LATEST_BROWSER_TAG }}"
                  body: "${{ env._LATEST_BROWSER_TAG }} [Original Changelog](https://github.com/bitwarden/clients/releases/tag/${{ env._LATEST_BROWSER_TAG }})"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  draft: false
                  allowUpdates: false
                  makeLatest: true
